# -*- coding: utf-8 -*-
#
# Gate One documentation build configuration file, created by
# sphinx-quickstart on Thu Sep 29 19:26:51 2011.

import sys, os, logging

# Use Tornado's pretty color log formatter
from tornado.log import LogFormatter
logger = logging.getLogger()
# Always set to debug because who else would be building the docs except a
# developer/sysadmin/geek?
logger.setLevel(getattr(logging, "DEBUG"))
for handler in list(logger.handlers): # Remove any existing log handlers
    if isinstance(handler, logging.StreamHandler):
        logger.handlers.remove(handler)
channel = logging.StreamHandler() # This ensures we're using Tornado's
channel.setFormatter(LogFormatter())
logger.addHandler(channel)

def bold(text):
    "Prints out *text* in bold inside a terminal"
    print("\x1b[1m{0}\x1b[0m".format(text))

# Check for dependencies
try:
    import sphinxcontrib.autojs
except ImportError:
    logging.error(
        "To build Gate One's docs you need the sphinxcontrib.autojs extension.")
    logging.info(
        "Liftoff Software maintains a fork of sphinxcontrib.autojs that "
        "includes additional fixes and ehancements (we submit pull requests but"
        " they can take time to make it back to the main repo) that can be "
        "cloned here:  https://github.com/liftoff/sphinxcontrib-autojs")
    bold("To fix this problem just do this:\n")
    bold(
        "    git clone "
        "https://github.com/liftoff/sphinxcontrib-autojs.git")
    bold("    cd sphinxcontrib-autojs; sudo python setup.py install")
    sys.exit(1)

try:
    import sphinxcontrib.ansi
except ImportError:
    logging.error(
        "To build Gate One's docs you need the sphinxcontrib.ansi extension.")
    bold("To fix this problem just do this:\n")
    bold("    sudo pip install sphinxcontrib-ansi")
    sys.exit(1)

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../../../'))
# Insert plugins too
for plugin_dir in os.listdir(os.path.abspath('../../plugins')):
    sys.path.append(os.path.abspath('../../plugins/%s' % plugin_dir))
# Insert application modules:
for app in os.listdir(os.path.abspath('../../applications')):
    app_dir = os.path.abspath('../../applications/%s' % app)
    if not os.path.isdir(app_dir):
        continue
    sys.path.append(app_dir)
    # ...and each of the application's plugins (if it has any):
    plugins_dir = os.path.join(app_dir, 'plugins')
    if os.path.exists(plugins_dir):
        for plugin_dir in os.listdir(plugins_dir):
            plugin_path = os.path.join(plugins_dir, plugin_dir)
            sys.path.append(plugin_path)

import gateone # So we can grab the version
# -- General configuration -----------------------------------------------------

# This is for using my custom stylesheet with the ANSI extension
def setup(app):
    app.add_stylesheet('ansi.css')

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.programoutput',
    'sphinxcontrib.ansi', # Displays text codes as they would appear in a shell
    'sphinxcontrib.autojs', # Lets us use docstring-like syntax in JS
]
try:
    # Add the googleanalytics extension if available
    import sphinxcontrib.googleanalytics
    extensions.append('sphinxcontrib.googleanalytics')
    googleanalytics_id = 'UA-29645087-2' # DM: Made this just for the docs
    googleanalytics_enabled = True
except ImportError:
    logging.info("FYI: You're missing the sphinxcontrib.googleanalytics module")

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Gate One'
copyright = u'2014, Liftoff Software Corporation'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
version = release = gateone.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

primary_domain = 'py'
default_role = 'py:obj'

autodoc_member_order = "bysource"
autoclass_content = "both"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'manni'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# Include TODOs in the docs.
todo_include_todos = True

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'default'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = "Gate One v%s" % gateone.__version__

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = "Gate One Documentation"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'Images/ls_logo_1inch_300dpi.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = 'Images/favicon.png'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = False

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'GateOneDoc'

html_output_encoding = 'utf-8'

# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
#latex_paper_size = 'letter'

# The font size ('10pt', '11pt' or '12pt').
#latex_font_size = '10pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'GateOne.tex', u'Gate One Documentation',
   u'Liftoff Software Corporation', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = 'Images/ls_logo_1inch_300dpi.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Additional stuff for the LaTeX preamble.
#latex_preamble = ''

# This is the current method (> Sphinx 0.5) of generating the preamble:
#latex_elements = {
    #'preamble': '''

     #'''
#}
#preamble = '''
#\makeatletter
#\ProvideTextCommandDefault\textcommabelow[1]
  #{\hmode@bgroup\ooalign{\null#1\crcr\hidewidth\raise-.31ex
   #\hbox{\check@mathfonts\fontsize\ssf@size\z@
   #\math@fontsfalse\selectfont,}\hidewidth}\egroup}
#\makeatother
#\usepackage{newunicodechar}
#\newunicodechar{Ș}{\textcommabelow S}
#\newunicodechar{ș}{\textcommabelow s}
#\newunicodechar{Ț}{\textcommabelow T}
#\newunicodechar{ț}{\textcommabelow t}
#'''
latex_elements = {
    'papersize':'letterpaper',
    'pointsize':'10pt',
    'classoptions': ',openany',
    'babel': '\\usepackage[english]{babel}',
    'inputenc': '',
    'utf8extra': '',
    #'preamble': preamble
    'preamble': '''
        \\usepackage{sphinx}
        \\hypersetup{unicode=true}
        \\usepackage{fontspec}
        \\setsansfont{Ubuntu}
        \\setromanfont{Ubuntu}
        \\setmonofont{Ubuntu Mono}
    '''
}
# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'gateone', u'Gate One Documentation',
     [u'Liftoff Software Corporation'], 1)
]


# -- Options for Epub output ---------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = u'Gate One'
epub_author = u'Dan McDougall'
epub_publisher = u'Liftoff Software Corporation'
epub_copyright = u'2011, Liftoff Software Corporation'

# The language of the text. It defaults to the language option
# or en if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
#epub_exclude_files = []

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# -- Intersphinx stuff ---------------------------------------------------------
intersphinx_mapping = {
    #'python': ('http://docs.python.org/2.7', None),
    #'tornado': ('http://www.tornadoweb.org/en/stable/', None)
}

# Make PHP syntax highlighting work
from sphinx.highlighting import lexers
from pygments.lexers.web import PhpLexer
lexers['php'] = PhpLexer(startinline=True)
